Repository ISIL-ESTE/Student-Workflow-Organizer, pull requests merged in 2023-07, with the labels that each got.

#56 Add user activation, metadata, routes, and soft delete logic; fix response path and server errors
  backend-app/.gitignore
  backend-app/app.js
  backend-app/config/app_config.js
  backend-app/config/logger_config.js
  backend-app/constants/meta_data.js
  backend-app/controllers/auth_controller.js
  backend-app/controllers/base_controller.js
  backend-app/controllers/user_controller.js
  backend-app/docs/admin.yaml
  backend-app/docs/auth.yaml
  backend-app/docs/super_admin.yaml
  backend-app/docs/user.yaml
  backend-app/middlewares/global_error_handler.js
  backend-app/middlewares/morgan.js
  backend-app/models/user_model.js
  backend-app/routes/auth_routes.js
  backend-app/utils/create_default_user.js
  backend-app/utils/swagger/index.js
  backend-app/utils/swagger/swaggergenerator.js
Labels: bug, enhancement, feature, fix

#75 Feat/token-based-authentication
  backend-app/.eslintrc.js
  backend-app/.prettierrc.json
  backend-app/config/app_config.js
  backend-app/controllers/auth_controller.js
  backend-app/models/token_model.js
  backend-app/package-lock.json
  backend-app/package.json
  backend-app/utils/authorization/generateTokens.js
Labels: enhancement, feature

#74 fix - rate limiter & duplicated methods & env variables
  backend-app/.env.example
  backend-app/app.js
  backend-app/config/app_config.js
  backend-app/config/logger_config.js
  backend-app/middlewares/rate_limit.js
  backend-app/models/user_model.js
  backend-app/routes/auth_routes.js
  backend-app/routes/github_routes.js
  backend-app/routes/users/admin_route.js
  backend-app/routes/users/super_admin_route.js
  backend-app/routes/users/user_route.js
  backend-app/server.js
  backend-app/utils/swagger/index.js
Labels: enhancement, feature, fix

#79 Creating CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, enhancement, good first issue, help wanted, suggest

#83 fix - Up date env variables : remove hard coded credentials
  backend-app/.env.example
  backend-app/.npmrc
  backend-app/app.js
  backend-app/config/app_config.js
  backend-app/controllers/user_controller.js
  backend-app/models/calendar/calendar_model.js
  backend-app/models/calendar/event_model.js
  backend-app/models/user/role_model.js
  backend-app/models/user/user_model.js
  backend-app/tests/e2e/login-signup.test.js
  backend-app/tests/init/roles.test.js
  backend-app/utils/authorization/role/role.js
  backend-app/utils/swagger/merge_yaml_files.js
Labels: bug, good first issue, invalid, fix
